/**
 * @file main_window.cpp
 * @brief Native C++ Qt6 Implementation of the Main UI (Phase 5)
 * Combines the UI interaction with the newly built C++ core AI logic.
 */

#include "main_window.h" 
// #include "ui_main_window.h" // Generated by Qt uic from .ui files

#include <QFileDialog>
#include <QMessageBox>
#include <QStackedWidget>
#include <QMenuBar>
#include <QStatusBar>
#include <QVBoxLayout>
#include <QFile>
#include <QThread>
#include "components/dashboard_widget.h"

// Include our Phase 1 & 3 Core Headers
#include "../core/project/ncktv_project.hpp"
#include "workers/transcription_worker.h"
#include "workers/vocal_separator_worker.h"
#include "wizard/wizard_mode.h"
#include "editor/editor_mode.h"
#include "dialogs/preferences_dialog.h"
#include "../core/config/config_manager.h"
#include "project/project.h"

namespace ncktv {

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    //, ui(new Ui::MainWindow)
{
    // ui->setupUi(this);

    // Initialize Config
    m_config = new ConfigManager("config.ini");

    // Initialize UI Layout
    setupApplicationUI();

    // Initialize the Core Data Structure directly mapped to C++ memory
    activeProject_ = std::make_shared<core::Project>();

    // Setup workers
    setupWorkers();
}

MainWindow::~MainWindow() {
    delete m_config;
    if (vocalThread_) {
        vocalThread_->quit();
        vocalThread_->wait();
    }
    if (transcriptionThread_) {
        transcriptionThread_->quit();
        transcriptionThread_->wait();
    }
}

void MainWindow::setupApplicationUI() {
    this->setWindowTitle("NC-KTV Pro Studio");
    this->resize(1400, 820);

    // Main layout
    QWidget* centralWidget = new QWidget(this);
    QVBoxLayout* layout = new QVBoxLayout(centralWidget);
    
    // Stacked widget manages Wizard vs Editor mode natively
    mainStack_ = new QStackedWidget(this);
    
    dashboardWidget_ = new DashboardWidget(this);
    wizardMode_ = new WizardMode(m_config, this);
    
    // EditorMode requires a project, we'll create it when the project is ready
    // editorMode_ = new EditorMode(activeProject_, this); 
    
    mainStack_->addWidget(dashboardWidget_);
    mainStack_->addWidget(wizardMode_);
    // if (editorMode_) mainStack_->addWidget(editorMode_);
    
    mainStack_->setCurrentWidget(dashboardWidget_);
    
    layout->addWidget(mainStack_);

    // Connect signals
    connect(dashboardWidget_, &DashboardWidget::newProjectRequested, this, &MainWindow::onActionNewProject);
    connect(dashboardWidget_, &DashboardWidget::openProjectRequested, this, &MainWindow::onActionOpenProject);
    
    connect(wizardMode_, &WizardMode::projectReady, this, &MainWindow::onProjectReady);
    connect(wizardMode_, &WizardMode::requestOpen, this, &MainWindow::onActionOpenProject);
    connect(wizardMode_, &WizardMode::requestNew, this, &MainWindow::onActionNewProject);
    connect(wizardMode_, &WizardMode::requestPreferences, this, [this]() {
        PreferencesDialog dialog(m_config, this);
        dialog.exec();
    });

    this->setCentralWidget(centralWidget);

    statusBar()->hide();

    // File menu
    QMenu* fileMenu = menuBar()->addMenu("File");
    fileMenu->addAction("New Project", this, &MainWindow::onActionNewProject, QKeySequence::New);
    fileMenu->addAction("Open Project...", this, &MainWindow::onActionOpenProject, QKeySequence::Open);
    fileMenu->addAction("Save Project", this, &MainWindow::onActionSaveProject, QKeySequence::Save);
    fileMenu->addAction("Save Project As...", this, &MainWindow::onActionSaveProjectAs, QKeySequence::SaveAs);
    fileMenu->addSeparator();
    fileMenu->addAction("Import...", this, [this]() { /* import */ });
    fileMenu->addAction("Export Video...", this, [this]() { if (editorMode_) editorMode_->onExportClicked(); });
    fileMenu->addSeparator();
    fileMenu->addAction("Preferences...", this, [this]() { PreferencesDialog d(m_config, this); d.exec(); });
    fileMenu->addSeparator();
    fileMenu->addAction("Exit", this, &QWidget::close, QKeySequence::Quit);

    // Edit menu
    QMenu* editMenu = menuBar()->addMenu("Edit");
    editMenu->addAction("Undo", QKeySequence::Undo);
    editMenu->addAction("Redo", QKeySequence::Redo);
    editMenu->addSeparator();
    editMenu->addAction("Preferences...", this, [this]() { PreferencesDialog d(m_config, this); d.exec(); });

    // Sequence menu (editor-only)
    m_sequenceMenu = menuBar()->addMenu("Sequence");
    m_sequenceMenu->addAction("Add Subtitle Line");
    m_sequenceMenu->addAction("Remove Selected Line");
    m_sequenceMenu->addAction("Split at Playhead");

    // Clip menu (editor-only)
    m_clipMenu = menuBar()->addMenu("Clip");
    m_clipMenu->addAction("Set In Point");
    m_clipMenu->addAction("Set Out Point");
    m_clipMenu->addAction("Clear In/Out");

    // Window menu (editor-only)
    m_windowMenu = menuBar()->addMenu("Window");
    m_windowMenu->addAction("Captions");
    m_windowMenu->addAction("Source Monitor");
    m_windowMenu->addAction("Program Monitor");
    m_windowMenu->addAction("Timeline");
    m_windowMenu->addAction("Tools");

    // Help menu
    QMenu* helpMenu = menuBar()->addMenu("Help");
    helpMenu->addAction("Keyboard Shortcuts");
    helpMenu->addAction("About NC-KTV Pro");

    setEditorMenusEnabled(false);

    // Load Pro Theme
    QFile qssFile(":/styles/dark_theme.qss");
    if (!qssFile.exists()) {
        // Try relative path fallback
        qssFile.setFileName(QCoreApplication::applicationDirPath() + "/styles/dark_theme.qss");
    }
    if (qssFile.open(QIODevice::ReadOnly | QIODevice::Text)) {
        this->setStyleSheet(qssFile.readAll());
        qssFile.close();
    }

    statusBar()->showMessage("NC-KTV Pro • Native C++ Engine Ready");
}

void MainWindow::setupWorkers() {
    // 1. Setup Vocal Separator Thread
    vocalThread_ = new QThread(this);
    vocalWorker_ = new VocalSeparatorWorker();
    vocalWorker_->moveToThread(vocalThread_);
    
    connect(vocalThread_, &QThread::finished, vocalWorker_, &QObject::deleteLater);
    connect(vocalWorker_, &VocalSeparatorWorker::progress, this, &MainWindow::onWorkerProgress);
    connect(vocalWorker_, &VocalSeparatorWorker::error, this, &MainWindow::onWorkerError);
    connect(vocalWorker_, &VocalSeparatorWorker::separationComplete, this, &MainWindow::onVocalSeparationFinished);
    
    vocalThread_->start();

    // 2. Setup Transcription Thread
    transcriptionThread_ = new QThread(this);
    transcriptionWorker_ = new TranscriptionWorker();
    transcriptionWorker_->moveToThread(transcriptionThread_);

    connect(transcriptionThread_, &QThread::finished, transcriptionWorker_, &QObject::deleteLater);
    connect(transcriptionWorker_, &TranscriptionWorker::progressUpdated, this, [this](const QString& msg){
         statusBar()->showMessage(msg);
    });
    connect(transcriptionWorker_, &TranscriptionWorker::error, this, &MainWindow::onWorkerError);
    connect(transcriptionWorker_, &TranscriptionWorker::transcriptionComplete, this, &MainWindow::onTranscriptionFinished);

    transcriptionThread_->start();
}

void MainWindow::setEditorMenusEnabled(bool enabled) {
    if (m_sequenceMenu) m_sequenceMenu->setEnabled(enabled);
    if (m_clipMenu) m_clipMenu->setEnabled(enabled);
    if (m_windowMenu) m_windowMenu->setEnabled(enabled);
}

void MainWindow::onActionNewProject() {
    // Reset wizard and switch to it
    wizardMode_->reset();
    mainStack_->setCurrentWidget(wizardMode_);
    setEditorMenusEnabled(false);
    statusBar()->showMessage("New Project Initialization...");
}

void MainWindow::onActionSaveProject() {
    if (!activeProject_) return;

    if (activeProject_->project_file.has_value() && !activeProject_->project_file->empty()) {
        saveProject(QString::fromStdString(activeProject_->project_file->string()));
    } else {
        onActionSaveProjectAs();
    }
}

void MainWindow::onActionSaveProjectAs() {
    if (!activeProject_) return;

    QString fileName = QFileDialog::getSaveFileName(this, "Save Project As", "", "NC-KTV Project (*.nctv)");
    if (!fileName.isEmpty()) {
        saveProject(fileName);
    }
}

void MainWindow::saveProject(const QString& fileName) {
    if (!activeProject_) return;

    // Convert activeProject_ (core::Project) to legacy Project
    Project legacy;
    legacy.setProjectName(QString::fromStdString(activeProject_->project_name));
    
    if (activeProject_->source_file.has_value())
        legacy.sourceFile = QString::fromStdString(activeProject_->source_file->string());
    
    if (activeProject_->audio_file.has_value())
        legacy.originalAudioPath = QString::fromStdString(activeProject_->audio_file->string());
        
    if (activeProject_->instrumental_file.has_value())
        legacy.instrumentalPath = QString::fromStdString(activeProject_->instrumental_file->string());
        
    if (activeProject_->vocals_file.has_value())
        legacy.vocalsPath = QString::fromStdString(activeProject_->vocals_file->string());

    // Sync Settings
    legacy.settings.uvrModel = QString::fromStdString(activeProject_->settings.uvr_model);
    legacy.settings.useGpu = activeProject_->settings.use_gpu;
    legacy.settings.sampleRate = activeProject_->settings.sample_rate;
    legacy.settings.karaokeStyle = QString::fromStdString(activeProject_->settings.karaoke_style);
    legacy.settings.outputFormat = QString::fromStdString(activeProject_->settings.output_format);

    // Sync Audio Clock
    legacy.audioClock.setSampleRate(activeProject_->audio_clock.get_sample_rate());
    legacy.audioClock.setMasterOffset(activeProject_->audio_clock.get_master_offset());
    for (const auto& [source, latency] : activeProject_->audio_clock.get_latencies()) {
        legacy.audioClock.setLatency(QString::fromStdString(source), latency);
    }

    // Sync Lyrics
    legacy.lyrics.clear();
    for (const auto& coreLine : activeProject_->lyrics.lines) {
        LyricLine line;
        line.text = QString::fromStdString(coreLine.text);
        line.startTime = coreLine.start_time;
        line.endTime = coreLine.end_time;
        
        for (const auto& token : coreLine.tokens) {
            line.addWord(QString::fromStdString(token.text), token.start_time, token.end_time);
        }
        legacy.lyrics.addLine(line);
    }

    // Sync Timeline
    legacy.timeline.tracks.clear();
    for (const auto& coreTrack : activeProject_->timeline.tracks) {
        Track legacyTrack;
        legacyTrack.trackId = QString::fromStdString(coreTrack.track_id);
        legacyTrack.name = QString::fromStdString(coreTrack.name);
        legacyTrack.isMuted = coreTrack.is_muted;
        legacyTrack.isSolo = coreTrack.is_solo;
        legacyTrack.isLocked = coreTrack.is_locked;
        
        // Track Type
        if (coreTrack.track_type == core::TrackType::AUDIO) legacyTrack.trackType = TrackType::Audio;
        else if (coreTrack.track_type == core::TrackType::VIDEO) legacyTrack.trackType = TrackType::Video;
        else if (coreTrack.track_type == core::TrackType::EFFECTS) legacyTrack.trackType = TrackType::Effects;
        else if (coreTrack.track_type == core::TrackType::LYRICS) legacyTrack.trackType = TrackType::Lyrics;

        for (const auto& coreClip : coreTrack.clips) {
            Clip legacyClip;
            legacyClip.clipId = QString::fromStdString(coreClip.clip_id);
            legacyClip.trackId = legacyTrack.trackId;
            legacyClip.startTime = coreClip.start_time;
            legacyClip.duration = coreClip.duration;
            if (coreClip.source_file.has_value())
                legacyClip.sourceFile = QString::fromStdString(*coreClip.source_file);
            legacyClip.sourceStart = coreClip.source_start;
            if (coreClip.source_end.has_value())
                legacyClip.sourceEnd = coreClip.source_end.value();
            
            legacyTrack.addClip(legacyClip);
        }
        legacy.timeline.tracks.push_back(legacyTrack);
    }

    try {
        legacy.save(fileName);
        activeProject_->project_file = fileName.toStdString();
        statusBar()->showMessage("Project saved: " + fileName, 3000);
    } catch (const std::exception& e) {
        QMessageBox::critical(this, "Save Failed", "Error saving project:\n" + QString::fromStdString(e.what()));
    }
}

void MainWindow::onActionOpenProject() {
    QString fileName = QFileDialog::getOpenFileName(this, "Open Project", "", "NC-KTV Project (*.nctv)");
    if (fileName.isEmpty()) return;

    try {
        Project legacy = Project::load(fileName);
        onProjectReady(&legacy);
        statusBar()->showMessage("Project loaded: " + fileName, 3000);
    } catch (const std::exception& e) {
        QMessageBox::critical(this, "Open Failed", "Error opening project:\n" + QString::fromStdString(e.what()));
    }
}

void MainWindow::onWorkerProgress(int percent, const QString& message) {
    statusBar()->showMessage(QString("[%1%] %2").arg(percent).arg(message));
}

void MainWindow::onWorkerError(const QString& errorMsg) {
    QMessageBox::critical(this, "Engine Fault", "Native Engine Error:\n" + errorMsg);
    statusBar()->showMessage("Task Aborted.");
}

void MainWindow::onVocalSeparationFinished(const QString& instPath, const QString& vocPath) {
    // 1. Assign completed tracks back to core Project format
    activeProject_->instrumental_file = instPath.toStdString();
    activeProject_->vocals_file = vocPath.toStdString();

    QMessageBox::information(this, "Phase 1 Complete", "Vocals separated natively via ONNX!");

    // 2. Cascade directly into Phase 3 Native Whisper Transcription via Thread-Safe Invocation
    statusBar()->showMessage("Commencing AI Lyrics Transcription...");
    QString whisperModel = m_config ? m_config->get<QString>("ai.whisper_model", "medium") : "medium";
    QString langCode = m_config ? m_config->get<QString>("ai.language", "auto") : "auto";
    if (langCode.toLower() == "auto") langCode = "auto";

    // Read engine preference
    QString engineStr = m_config ? m_config->get<QString>("ai.transcription_engine", "whisperx") : "whisperx";
    TranscriptionEngine engine = (engineStr == "whisper")
        ? TranscriptionEngine::Whisper
        : TranscriptionEngine::WhisperX;

    QMetaObject::invokeMethod(transcriptionWorker_, "startTranscription", Qt::QueuedConnection,
                              Q_ARG(QString, vocPath),
                              Q_ARG(QString, whisperModel),
                              Q_ARG(QString, langCode),
                              Q_ARG(ncktv::TranscriptionEngine, engine));
}

void MainWindow::onTranscriptionFinished(const QString& resultJson) {
    statusBar()->showMessage("Transcription Complete. Transitioning to Editor.");

    // TODO: Parse standard JSON into activeProject_->lyrics data structures. 
    if (editorMode_) {
        mainStack_->setCurrentWidget(editorMode_);
    }
}

void MainWindow::onProjectReady(Project* project) {
    if (!project) return;
    
    QString pName = project->projectName();
    if (pName.isEmpty() && project->sourceFile.has_value()) {
        pName = QFileInfo(*project->sourceFile).baseName();
    }
    this->setWindowTitle(pName + " - NC-KTV Pro Studio");

    statusBar()->showMessage("Project ready. Syncing data and launching Editor...");
    
    // 1. Sync Paths
    if (project->sourceFile.has_value())
        activeProject_->source_file = project->sourceFile->toStdString();
    
    if (project->instrumentalPath.has_value())
        activeProject_->instrumental_file = project->instrumentalPath->toStdString();
    
    if (project->vocalsPath.has_value())
        activeProject_->vocals_file = project->vocalsPath->toStdString();
        
    if (project->originalAudioPath.has_value())
        activeProject_->audio_file = project->originalAudioPath->toStdString();
    
    if (project->projectFilePath.has_value())
        activeProject_->project_file = project->projectFilePath->toStdString();

    // 1.5 Sync Settings and Audio Clock
    activeProject_->settings.uvr_model = project->settings.uvrModel.toStdString();
    activeProject_->settings.use_gpu = project->settings.useGpu;
    activeProject_->settings.sample_rate = project->settings.sampleRate;
    activeProject_->settings.karaoke_style = project->settings.karaokeStyle.toStdString();
    activeProject_->settings.output_format = project->settings.outputFormat.toStdString();

    activeProject_->audio_clock.set_sample_rate(project->audioClock.sampleRate());
    activeProject_->audio_clock.set_master_offset(project->audioClock.masterOffset());
    const auto& latencies = project->audioClock.getLatencies();
    for (auto it = latencies.begin(); it != latencies.end(); ++it) {
        activeProject_->audio_clock.set_latency(it.key().toStdString(), it.value());
    }

    // 2. Convert Lyrics from ncktv::LyricsData (Qt/QString) to ncktv::core::LyricsData (std::string)
    activeProject_->lyrics.clear();
    for (const auto& legacyLine : project->lyrics.lines) {
        core::LyricsLine coreLine;
        coreLine.text = legacyLine.text.toStdString();
        coreLine.start_time = static_cast<float>(legacyLine.startTime);
        coreLine.end_time = static_cast<float>(legacyLine.endTime);
        
        for (const auto& legacyWord : legacyLine.words) {
            coreLine.tokens.emplace_back(
                legacyWord.word.toStdString(),
                static_cast<float>(legacyWord.startTime),
                static_cast<float>(legacyWord.endTime)
            );
        }
        
        activeProject_->lyrics.lines.push_back(std::move(coreLine));
    }

    // 2.5 Sync Timeline
    activeProject_->timeline.clear();
    for (const auto& legacyTrack : project->timeline.tracks) {
        core::Track coreTrack;
        coreTrack.track_id = legacyTrack.trackId.toStdString();
        coreTrack.name = legacyTrack.name.toStdString();
        coreTrack.is_muted = legacyTrack.isMuted;
        coreTrack.is_solo = legacyTrack.isSolo;
        coreTrack.is_locked = legacyTrack.isLocked;

        // Track Type
        if (legacyTrack.trackType == TrackType::Audio) coreTrack.track_type = core::TrackType::AUDIO;
        else if (legacyTrack.trackType == TrackType::Video) coreTrack.track_type = core::TrackType::VIDEO;
        else if (legacyTrack.trackType == TrackType::Effects) coreTrack.track_type = core::TrackType::EFFECTS;
        else if (legacyTrack.trackType == TrackType::Lyrics) coreTrack.track_type = core::TrackType::LYRICS;

        for (const auto& legacyClip : legacyTrack.clips) {
            core::Clip coreClip;
            coreClip.clip_id = legacyClip.clipId.toStdString();
            coreClip.track_id = coreTrack.track_id;
            coreClip.start_time = static_cast<float>(legacyClip.startTime);
            coreClip.duration = static_cast<float>(legacyClip.duration);
            if (legacyClip.sourceFile.has_value())
                coreClip.source_file = legacyClip.sourceFile->toStdString();
            coreClip.source_start = static_cast<float>(legacyClip.sourceStart);
            if (legacyClip.sourceEnd.has_value())
                coreClip.source_end = static_cast<float>(legacyClip.sourceEnd.value());
            
            coreTrack.add_clip(std::move(coreClip));
        }
        activeProject_->timeline.add_track(std::move(coreTrack));
    }

    // 3. Launch Editor
    if (editorMode_) {
        mainStack_->removeWidget(editorMode_);
        delete editorMode_;
    }
    
    editorMode_ = new EditorMode(activeProject_, m_config, this);
    connect(editorMode_, &EditorMode::requestSave, this, &MainWindow::onActionSaveProject);
    connect(editorMode_, &EditorMode::requestSaveAs, this, &MainWindow::onActionSaveProjectAs);
    connect(editorMode_, &EditorMode::requestOpen, this, &MainWindow::onActionOpenProject);
    connect(editorMode_, &EditorMode::requestNew, this, &MainWindow::onActionNewProject);
    connect(editorMode_, &EditorMode::requestPreferences, this, [this]() {
        PreferencesDialog dialog(m_config, this);
        dialog.exec();
    });
    connect(editorMode_, &EditorMode::requestExport, editorMode_, &EditorMode::onExportClicked);
    
    mainStack_->addWidget(editorMode_);
    mainStack_->setCurrentWidget(editorMode_);
    setEditorMenusEnabled(true);
}

} // namespace ncktv
