/**
 * @file main_window.cpp
 * @brief Native C++ Qt6 Implementation of the Main UI (Phase 5)
 * Combines the UI interaction with the newly built C++ core AI logic.
 */

#include "main_window.h" 
// #include "ui_main_window.h" // Generated by Qt uic from .ui files

#include <QFileDialog>
#include <QMessageBox>
#include <QStackedWidget>
#include <QMenuBar>
#include <QStatusBar>
#include <QVBoxLayout>

// Include our Phase 1 & 3 Core Headers
#include "../core/project/ncktv_project.hpp"
#include "workers/transcription_worker.h"
#include "workers/vocal_separator_worker.h"
#include "wizard/wizard_mode.h"
#include "editor/editor_mode.h"

namespace ncktv {

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    //, ui(new Ui::MainWindow)
{
    // ui->setupUi(this);

    // Initialize UI Layout
    setupApplicationUI();

    // Initialize the Core Data Structure directly mapped to C++ memory
    activeProject_ = std::make_shared<core::Project>();

    // Setup workers
    setupWorkers();
}

MainWindow::~MainWindow() {
    if (vocalThread_) {
        vocalThread_->quit();
        vocalThread_->wait();
    }
    if (transcriptionThread_) {
        transcriptionThread_->quit();
        transcriptionThread_->wait();
    }
}

void MainWindow::setupApplicationUI() {
    this->setWindowTitle("NC-KTV Developer Console (100% C++ Mode)");
    this->resize(1280, 720);

    // Main layout
    QWidget* centralWidget = new QWidget(this);
    QVBoxLayout* layout = new QVBoxLayout(centralWidget);
    
    // Stacked widget manages Wizard vs Editor mode natively
    mainStack_ = new QStackedWidget(this);
    wizardMode_ = new WizardMode(this);
    
    // EditorMode requires a project, we'll create it when the project is ready
    // editorMode_ = new EditorMode(activeProject_, this); 
    
    mainStack_->addWidget(wizardMode_);
    // if (editorMode_) mainStack_->addWidget(editorMode_);
    
    layout->addWidget(mainStack_);

    // Connect signals
    connect(wizardMode_, &WizardMode::projectReady, this, &MainWindow::onProjectReady);

    this->setCentralWidget(centralWidget);

    // Setup Menus
    QMenu* fileMenu = menuBar()->addMenu("&File");
    QAction* newAction = fileMenu->addAction("New Project (Native)...", this, &MainWindow::onActionNewProject);
    newAction->setShortcut(QKeySequence::New);

    statusBar()->showMessage("Native C++ Core initialized. Zero Python Runtime detected.");
}

void MainWindow::setupWorkers() {
    // 1. Setup Vocal Separator Thread
    vocalThread_ = new QThread(this);
    vocalWorker_ = new VocalSeparatorWorker();
    vocalWorker_->moveToThread(vocalThread_);
    
    connect(vocalThread_, &QThread::finished, vocalWorker_, &QObject::deleteLater);
    connect(vocalWorker_, &VocalSeparatorWorker::progress, this, &MainWindow::onWorkerProgress);
    connect(vocalWorker_, &VocalSeparatorWorker::error, this, &MainWindow::onWorkerError);
    connect(vocalWorker_, &VocalSeparatorWorker::separationComplete, this, &MainWindow::onVocalSeparationFinished);
    
    vocalThread_->start();

    // 2. Setup Transcription Thread
    transcriptionThread_ = new QThread(this);
    transcriptionWorker_ = new TranscriptionWorker();
    transcriptionWorker_->moveToThread(transcriptionThread_);

    connect(transcriptionThread_, &QThread::finished, transcriptionWorker_, &QObject::deleteLater);
    connect(transcriptionWorker_, &TranscriptionWorker::progressUpdated, this, [this](const QString& msg){
         statusBar()->showMessage(msg);
    });
    connect(transcriptionWorker_, &TranscriptionWorker::error, this, &MainWindow::onWorkerError);
    connect(transcriptionWorker_, &TranscriptionWorker::transcriptionComplete, this, &MainWindow::onTranscriptionFinished);

    transcriptionThread_->start();
}

void MainWindow::onActionNewProject() {
    QString videoFile = QFileDialog::getOpenFileName(this, "Select Media File", "", "Media Files (*.mp4 *.mkv *.wav)");
    if (videoFile.isEmpty()) return;

    // Utilize Phase 1 structures natively
    activeProject_->source_file = videoFile.toStdString();
    activeProject_->project_name = QFileInfo(videoFile).baseName().toStdString();

    statusBar()->showMessage("Commencing Neural Separation...");

    // Trigger Phase 3 Native ONNX via Thread-Safe Invocation
    QString outDir = QDir::currentPath() + "/temp/project_" + QFileInfo(videoFile).baseName();
    
    QMetaObject::invokeMethod(vocalWorker_, "startSeparation", Qt::QueuedConnection,
                              Q_ARG(QString, videoFile),
                              Q_ARG(QString, QString::fromStdString(activeProject_->settings.uvr_model)),
                              Q_ARG(QString, outDir));
}

void MainWindow::onWorkerProgress(int percent, const QString& message) {
    statusBar()->showMessage(QString("[%1%] %2").arg(percent).arg(message));
}

void MainWindow::onWorkerError(const QString& errorMsg) {
    QMessageBox::critical(this, "Engine Fault", "Native Engine Error:\n" + errorMsg);
    statusBar()->showMessage("Task Aborted.");
}

void MainWindow::onVocalSeparationFinished(const QString& instPath, const QString& vocPath) {
    // 1. Assign completed tracks back to core Project format
    activeProject_->instrumental_file = instPath.toStdString();
    activeProject_->vocals_file = vocPath.toStdString();

    QMessageBox::information(this, "Phase 1 Complete", "Vocals separated natively via ONNX!");

    // 2. Cascade directly into Phase 3 Native Whisper Transcription via Thread-Safe Invocation
    statusBar()->showMessage("Commencing AI Lyrics Transcription...");
    QMetaObject::invokeMethod(transcriptionWorker_, "startTranscription", Qt::QueuedConnection,
                              Q_ARG(QString, vocPath),
                              Q_ARG(QString, "ggml-large-v3.bin"),
                              Q_ARG(QString, "auto"));
}

void MainWindow::onTranscriptionFinished(const QString& resultJson) {
    statusBar()->showMessage("Transcription Complete. Transitioning to Editor.");

    // TODO: Parse standard JSON into activeProject_->lyrics data structures. 
    if (editorMode_) {
        mainStack_->setCurrentWidget(editorMode_);
    }
}

void MainWindow::onProjectReady(Project* project) {
    if (!project) return;
    
    statusBar()->showMessage("Project ready. Syncing data and launching Editor...");
    
    // 1. Sync Paths
    if (project->sourceFile.has_value())
        activeProject_->source_file = project->sourceFile->toStdString();
    
    if (project->instrumentalPath.has_value())
        activeProject_->instrumental_file = project->instrumentalPath->toStdString();
    
    if (project->vocalsPath.has_value())
        activeProject_->vocals_file = project->vocalsPath->toStdString();
        
    if (project->originalAudioPath.has_value())
        activeProject_->audio_file = project->originalAudioPath->toStdString();

    // 2. Convert Lyrics from ncktv::LyricsData (Qt/QString) to ncktv::core::LyricsData (std::string)
    activeProject_->lyrics.clear();
    for (const auto& legacyLine : project->lyrics.lines) {
        core::LyricsLine coreLine;
        coreLine.text = legacyLine.text.toStdString();
        coreLine.start_time = static_cast<float>(legacyLine.startTime);
        coreLine.end_time = static_cast<float>(legacyLine.endTime);
        
        for (const auto& legacyWord : legacyLine.words) {
            coreLine.tokens.emplace_back(
                legacyWord.word.toStdString(),
                static_cast<float>(legacyWord.startTime),
                static_cast<float>(legacyWord.endTime)
            );
        }
        
        activeProject_->lyrics.lines.push_back(std::move(coreLine));
    }

    // 3. Launch Editor
    if (editorMode_) {
        mainStack_->removeWidget(editorMode_);
        delete editorMode_;
    }
    
    editorMode_ = new EditorMode(activeProject_, this);
    mainStack_->addWidget(editorMode_);
    mainStack_->setCurrentWidget(editorMode_);
}

} // namespace ncktv
